import { launch, gesture, fw, check, summary, shotDir, appDir } from './lib.mjs'
import { writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const executablePath = process.argv.includes('packaged') ? join(appDir, 'dist', 'win-unpacked', 'Floating Whiteboard.exe') : undefined
let session = await launch({ executablePath })
let { app, page, userData } = session
const errors = []
const observe = () => page.on('pageerror', error => errors.push(error.message))
observe()
const saved = () => page.waitForFunction(() => window.__fw.S.saveStatus.value === 'saved' && !window.__fw.S.settingsError.value)
const selectBox = () => fw(page, w => w.board.doc.bounds(w.board.selection))
const screenshot = async name => { await page.waitForTimeout(180); await page.screenshot({ path: join(shotDir, name + '.png') }) }

try {
  await page.waitForFunction(() => window.__fw.S.ready.value)
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setBounds({ x: 40, y: 40, width: 1180, height: 760 }))
  await fw(page, w => { w.S.radialEnabled.value = false; w.S.bgAlpha.value = 100; w.board.setView({ x: 0, y: 0, zoom: 1 }) })

  await page.keyboard.press('t'); await gesture(page, [[190, 150]])
  const text = page.getByRole('textbox', { name: 'Text content', exact: true })
  await text.fill('A better whiteboard\nWrite. Arrange. Explain.')
  check('text tool opens a focused inline editor', await text.evaluate(el => el === document.activeElement))
  check('in-progress text is included in autosave without a committed object', await fw(page, w => w.board.doc.items.length === 0 && JSON.parse(w.board.serialize()).items[0].text.includes('Arrange')))
  await text.press('Control+Enter')
  check('finish creates one editable text object', await fw(page, w => w.board.doc.items.length === 1 && w.board.doc.items[0].t === 't' && !w.S.editing.value))
  await page.getByRole('button', { name: 'Object style', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Font size' }).fill('30')
  await page.getByRole('button', { name: 'Bold', exact: true }).click()
  check('context controls apply font size and bold', await fw(page, w => w.board.selection[0].fontSize === 30 && w.board.selection[0].bold))
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape')

  await page.keyboard.press('n'); await gesture(page, [[200, 390]])
  const note = page.getByRole('textbox', { name: 'Sticky note text' })
  await note.fill('Lesson ideas\nKeep objects editable\nUndo every step')
  await note.press('Control+Enter')
  await page.getByRole('button', { name: 'Object style', exact: true }).click()
  await page.getByRole('button', { name: 'Fill #d3e6ff', exact: true }).click()
  await page.getByRole('button', { name: 'Bulleted list', exact: true }).click()
  check('sticky notes keep text, fill and list style', await fw(page, w => w.board.selection[0].note && w.board.selection[0].fill === '#d3e6ff' && w.board.selection[0].list === 'bullet'))
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape')

  await page.keyboard.press('r'); await gesture(page, [[640, 180], [900, 300]])
  await page.keyboard.press('v'); await gesture(page, [[770, 240]])
  check('unfilled shapes can be selected through their interior', await fw(page, w => w.board.selection[0]?.k === 'rect'))
  await page.keyboard.press('Enter')
  const label = page.getByRole('textbox', { name: 'Shape label' })
  await label.fill('Start with an idea'); await label.press('Control+Enter')
  await page.getByRole('button', { name: 'Object style', exact: true }).click()
  await page.getByRole('button', { name: 'Fill #d7f0dd', exact: true }).click()
  await page.getByRole('button', { name: 'dashed border', exact: true }).click()
  await page.getByRole('slider', { name: 'Corners', exact: true }).evaluate(el => { el.value = '18'; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })) })
  check('shape labels and border controls persist together', await fw(page, w => { const s = w.board.selection[0]; return s.text === 'Start with an idea' && s.fill === '#d7f0dd' && s.dash === 'dashed' && s.radius === 18 }))
  await page.getByRole('button', { name: 'No fill', exact: true }).click()
  await saved()
  check('No fill is a valid saveable style', await fw(page, w => w.board.selection[0].fill === 'none' && !w.S.saveError.value))
  await page.getByRole('button', { name: 'Fill #d7f0dd', exact: true }).click()
  await screenshot('phase2-object-style')
  await page.keyboard.press('Escape')
  await fw(page, w => w.board.setSelection([w.board.doc.items.find(it => it.t === 'h')]))

  const b = await selectBox()
  const beforeResize = await fw(page, w => structuredClone(w.board.selection[0]))
  await gesture(page, [[b[2], b[3]], [b[2] + 70, b[3] + 40]])
  check('corner handle resizes the object', await fw(page, (w, before) => w.board.selection[0].p[2] - w.board.selection[0].p[0] > before.p[2] - before.p[0] + 50, beforeResize))
  await page.keyboard.press('Control+z')
  check('one undo restores the entire resize', await fw(page, (w, before) => JSON.stringify(w.board.selection[0]) === JSON.stringify(before), beforeResize))
  const rotBounds = await selectBox(), center = [(rotBounds[0] + rotBounds[2]) / 2, (rotBounds[1] + rotBounds[3]) / 2]
  check('rotation handle is not covered by the selection toolbar', await page.evaluate(([x, y]) => document.elementFromPoint(x, y)?.classList.contains('stage'), [center[0], rotBounds[1] - 28]))
  await gesture(page, [[center[0], rotBounds[1] - 28], [rotBounds[2] + 28, center[1]]], { shift: true })
  check('rotation handle rotates the shape and label together', await fw(page, w => Math.abs(w.board.selection[0].angle - Math.PI / 2) < .001))
  await page.keyboard.press('Control+z')

  await page.keyboard.press('Control+a'); await page.keyboard.press('Control+g')
  const group = await fw(page, w => w.board.selection[0].group)
  check('grouping creates one persistent group', await fw(page, (w, g) => !!g && w.board.selection.length === 3 && w.board.selection.every(it => it.group === g), group))
  await page.keyboard.press('Control+d')
  check('duplicated groups have independent IDs and membership', await fw(page, (w, g) => w.board.doc.items.length === 6 && w.board.selection.every(it => it.group && it.group !== g) && new Set(w.board.doc.items.map(it => it.id)).size === 6, group))
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Control+a'); await page.keyboard.press('Control+Shift+g')
  check('ungroup keeps all objects and clears membership', await fw(page, w => w.board.doc.items.length === 3 && w.board.selection.every(it => !it.group)))

  await fw(page, w => w.board.setSelection([w.board.doc.items[1]]))
  await page.keyboard.press('Control+l')
  const lockedBefore = await fw(page, w => JSON.stringify(w.board.selection[0]))
  await gesture(page, [[250, 440], [310, 450]])
  await page.keyboard.press('Delete')
  check('locked note can be selected but cannot be moved or deleted', await fw(page, (w, before) => w.board.doc.items.length === 3 && JSON.stringify(w.board.doc.items[1]) === before, lockedBefore))
  await page.getByRole('button', { name: 'Unlock selection', exact: true }).click()
  check('unlock is available directly on the selection', await fw(page, w => !w.board.selection[0].locked))
  await page.keyboard.press('ArrowRight'); await page.keyboard.press('Shift+ArrowDown')
  check('keyboard nudge supports fine and coarse steps', await fw(page, w => w.board.selection[0].p[0] === 201 && w.board.selection[0].p[1] === 400))

  await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v')
  check('object copy and paste keeps text and styling editable', await fw(page, w => w.board.doc.items.length === 4 && w.board.selection[0].note && w.board.selection[0].text.includes('Lesson')))
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Escape'); await page.keyboard.press('q')
  await gesture(page, [[175, 375], [455, 375], [455, 650], [175, 650], [175, 375]])
  check('lasso selects the enclosed note', await fw(page, w => w.board.selection.length === 1 && w.board.selection[0].note))
  await page.keyboard.press('v')

  // User-facing edit focus and cancellation must leave both content and history intact.
  await page.keyboard.press('Enter')
  await page.getByRole('textbox', { name: 'Sticky note text' }).fill('Discard this edit')
  await page.keyboard.press('Escape')
  check('Escape restores original text and exits inline editing', await fw(page, w => !w.S.editing.value && w.board.selection[0].text.includes('Lesson')))

  await page.keyboard.press('Control+a')
  const plainTextBefore = await fw(page, w => JSON.stringify(w.board.doc.items.find(it => it.t === 't' && !it.note)))
  await page.getByRole('button', { name: 'Object style', exact: true }).click()
  await page.getByRole('button', { name: 'Fill #e7d9ff', exact: true }).click()
  check('mixed selection fill changes only compatible objects', await fw(page, (w, before) => JSON.stringify(w.board.doc.items.find(it => it.t === 't' && !it.note)) === before && w.board.doc.items.filter(it => it.note || it.t === 'h').every(it => it.fill === '#e7d9ff'), plainTextBefore))
  await page.keyboard.press('Escape'); await page.keyboard.press('Control+z')
  await fw(page, w => w.board.setSelection([w.board.doc.items.find(it => it.t === 'h')]))
  await page.keyboard.press('Control+Alt+c')
  await fw(page, w => w.board.setSelection([w.board.doc.items.find(it => it.note)]))
  await page.keyboard.press('Control+Alt+v')
  check('pasting a default style clears previous bold and list formatting', await fw(page, w => w.board.selection[0].list === 'none' && w.board.selection[0].bold === false && w.board.selection[0].fill === '#d7f0dd'))
  await page.keyboard.press('Control+z')

  await fw(page, w => w.board.setSelection([w.board.doc.items[0]]))
  await page.keyboard.press('PageUp')
  check('front ordering is undoable without losing selection', await fw(page, w => w.board.doc.items.at(-1) === w.board.selection[0] && w.board.selection[0].text.startsWith('A better')))
  await page.keyboard.press('Control+z')
  await fw(page, w => { w.board.setView({ x: 120, y: 80, zoom: .65 }); w.board.setSelection([w.board.doc.items[0]]) })
  await page.keyboard.press('Enter')
  check('inline editing follows the board position and zoom', await page.locator('.inline-editor').evaluate(el => { const r = el.getBoundingClientRect(), { board } = window.__fw, it = window.__fw.S.editing.value.item; return Math.abs(r.left - (it.p[0] - board.view.x) * board.view.zoom) < 1 && Math.abs(r.width - (it.p[2] - it.p[0]) * board.view.zoom) < 1 }))
  await page.keyboard.press('Escape')
  await fw(page, w => w.board.setView({ x: 0, y: 0, zoom: 1 }))
  const textBounds = await selectBox(), originalText = await fw(page, w => structuredClone(w.board.selection[0]))
  await gesture(page, [[textBounds[2], (textBounds[1] + textBounds[3]) / 2], [textBounds[2] - 150, (textBounds[1] + textBounds[3]) / 2]])
  check('narrowing text preserves font size and grows to fit wrapped content', await fw(page, (w, before) => { const it = w.board.selection[0]; return it.fontSize === before.fontSize && it.p[2] - it.p[0] < before.p[2] - before.p[0] - 100 && it.p[3] - it.p[1] > before.p[3] - before.p[1] }, originalText))
  await page.keyboard.press('Control+z')
  await fw(page, w => w.board.setSelection([w.board.doc.items.find(it => it.t === 'h')]))
  const beforeCancelledDrag = await fw(page, w => JSON.stringify(w.board.selection[0]))
  await gesture(page, [[770, 240], [790, 265]], { up: false })
  await page.keyboard.press('Escape')
  await gesture(page, [[790, 265]], { down: false })
  check('Escape cancels an active drag without changing the object', await fw(page, (w, before) => !w.S.gestureActive.value && JSON.stringify(w.board.doc.items.find(it => it.t === 'h')) === before, beforeCancelledDrag))
  await page.mouse.dblclick(770, 240)
  check('double-click opens a shape label for editing', await page.getByRole('textbox', { name: 'Shape label' }).isVisible())
  await page.keyboard.press('Escape')
  await fw(page, w => w.board.setSelection([w.board.doc.items.find(it => it.note)]))
  await saved()
  const json = await fw(page, w => w.board.serialize())
  check('saved format includes editable Phase 2 objects', JSON.parse(json).version === 2 && JSON.parse(json).items.length === 3)
  const png = await fw(page, async w => Array.from(new Uint8Array(await w.board.exportPng('#ffffff', true))))
  writeFileSync(join(shotDir, 'phase2-export.png'), Buffer.from(png))
  check('PNG export contains a valid rendered image', png[0] === 137 && png[1] === 80 && png.length > 10000)
  await screenshot('phase2-board')

  // Close while text still has focus; reopening must retain the draft.
  await page.keyboard.press('Enter')
  await page.getByRole('textbox', { name: 'Sticky note text' }).fill('Saved while still editing\nReady for the next lesson')
  await app.close()
  const disk = JSON.parse(readFileSync(join(userData, 'board.json'), 'utf8'))
  check('closing flushes in-progress text to disk', disk.items.some(it => it.text?.includes('Saved while still editing')))
  session = await launch({ userData, executablePath }); ({ app, page } = session); observe()
  await page.waitForFunction(() => window.__fw.S.ready.value)
  check('reopen restores text, shapes and styles', await fw(page, w => w.board.doc.items.length === 3 && w.board.doc.items.some(it => it.text?.includes('Saved while still editing')) && w.board.doc.items.some(it => it.fill === '#d7f0dd')))

  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setBounds({ width: 420, height: 320 }))
  await fw(page, w => { w.board.setView({ x: 120, y: 340, zoom: .65 }); w.board.setTool('select'); w.board.setSelection([w.board.doc.items.find(it => it.note)]) })
  await page.getByRole('button', { name: 'Object style', exact: true }).click()
  check('context controls stay within the minimum window', await page.locator('.selection-tools').evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth + 1 && r.top >= 0 && r.bottom <= innerHeight + 1 }))
  check('all dock tools remain visible in a small window', await page.locator('.dock').evaluate(el => { const r = el.getBoundingClientRect(); return r.top >= 28 && r.bottom < innerHeight - 25 }))
  await screenshot('phase2-small-window')
  check('no renderer errors occurred', errors.length === 0, errors.join('\n'))
} finally { await app.close().catch(() => {}) }
process.exit(summary() ? 1 : 0)
